---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
  name:  storage-inspector-pod-manager
rules:  
  - apiGroups:
      - ""
      - "rbac.authorization.k8s.io"
    resources:
      - pods
      - services
      - services/finalizers
      - serviceaccounts
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - roles
      - rolebindings
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-inspector-controller    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-inspector-admin-binding
subjects:
  - kind: ServiceAccount
    name: storage-inspector-controller   
    namespace: inspector   
roleRef:
  kind: ClusterRole
  name: storage-inspector-pod-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-inspector-deployment
  labels:
    app: k8s-ephemeral-storage-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ephemeral-storage-inspector
  template:
    metadata:
      labels:
        app: k8s-ephemeral-storage-inspector
    spec:
      serviceAccountName: storage-inspector-controller  
      containers:
      - name: k8s-ephemeral-storage-inspector
        image: bmoussaud/k8s-ephemeral-storage-inspector:0.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: BS
            value: "512M"
          - name: OUTPUT_DIRECTORY
            value: "/tmp/filler"
          - name: ENGINE
            value: K8S
          - name: PORT
            value: "5000"
        volumeMounts:
          - mountPath: /tmp/filler
            name: runner
      volumes:
        - name: runner
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: storage-inspector-svc
spec:
  selector:
    app: k8s-ephemeral-storage-inspector
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


