---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
  name:  fill-app-pod-manager
rules:  
  - apiGroups:
      - ""
      - "rbac.authorization.k8s.io"
    resources:
      - pods
      - services
      - services/finalizers
      - serviceaccounts
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - roles
      - rolebindings
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
      - post
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fill-app-controller    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fill-app-admin-binding
subjects:
  - kind: ServiceAccount
    name: fill-app-controller   
    namespace: filler   
roleRef:
  kind: ClusterRole
  name: fill-app-pod-manager
  apiGroup: rbac.authorization.k8s.io
