apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: fill-storage-image
  namespace: default
spec:
  tag: bmoussaud/k8s-ephemeral-storage-inspector:kpack
  serviceAccount: fill-storage-registry-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4